# Generated by Django 3.1.2 on 2020-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
